### ISSUE TITLE
Error in starting up demo with ACME - something has changed somewhere

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-acapy-controllers#10]
Here's the error:

```
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo webstart
Starting all agents and controllers, this may take a moment.
Creating network "docker_aca" with the default driver
Building acme-agent
ERROR: error fetching: fatal: couldn't find remote ref acme-complete
: exit status 128
```

Looks like something happened with the Acme branch?

Maybe the best answer is to have a copy of the complete Acme in this repo?

@amanji - do you have any time to take a look at this in the next few days - before the course launches?  If not, I can dig in.  Please let me know.

**Comment by amanji** [comment]
I will get on this right away. Thanks for the heads up
