### ISSUE TITLE
Alice controller cant connect to agent

### ISSUE THREAD

**Issue by biligunb** [hyperledger/aries-acapy-controllers#17]
1. Prerequisites are all OK
2. docker containers are started
3. x.x.x.x:8031 : agent is running
4. x.x.x.x:9031 : Alice controller is running but shows RED indicator.
   - cant connect to agent  

```
If the controller is not connected to it's agent you will see a red status indicator on the top right-hand side of the navbar. 
If the agent is succesffully connected, you will see a green status indicator.
```

![image](https://user-images.githubusercontent.com/26878066/75953103-921e3480-5eeb-11ea-937b-ef17c769cd84.png)

---

Tried on AWS EC2 : ubuntu 18.04  
![image](https://user-images.githubusercontent.com/26878066/75953235-e6291900-5eeb-11ea-8be5-f5c264495360.png)

**Comment by amanji** [comment]
Were you able to connect to the other controllers on your EC2 instance? Do you perhaps have any specific port rules enabled? Also wondering if you tried running the demo either locally, or through Play With Docker (PWD)?

**Comment by biligunb** [comment]
Other 2 was fine.
I tried it on my local machine (Ubuntu)
And all 3 controllers & agents were OK.

I don't know why it failed on AWS EC2 all ports were open

**Comment by amanji** [comment]
I suspect it is because of how the IP addresses are configured for controller to agent connections. Thank you for the heads up. I will continue testing and see if I can get an AWS setup completely working.

**Comment by biligunb** [comment]
I looked around the source code and I saw that Alice front-end had configured (from ENV variable)
AGENT host. if NOT provided it was using (localhost as default)
Perhaps that could be the reason.

**Comment by amanji** [comment]
That was exactly it. I have a fix which I'll issue a PR for, which is to set the agent host to the `ALICE_AGENT_HOST` environment variable if the user specifies it at the `run_demo` command or default to `localhost`. This would allow users to deploy the controller on cloud instances.
