### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by juvebogdan** [hyperledger/aries-acapy-controllers#29]
Hello,

In your docker-compose file there is a line dockerfile: ./docker/Dockerfile.demo

This file does not exist there.

How can I run this?

Thank you

**Comment by amanji** [comment]
It's an external build context for an ACA-Py agent (which the controller will need to operate). The agent is built from a different [repository](https://github.com/petridishdev/aries-cloudagent-python/tree/master/docker) therefore the path specified to `Dockerfile.demo` is from the root of that repo.
