### ISSUE TITLE
ERROR: dotnet run -p FaberController

### ISSUE THREAD

**Issue by KimhengSOK** [hyperledger/aries-acapy-controllers#42]
Dear all,

I  am trying to run the faber controller and it produces error message as belows:

/usr/share/dotnet/sdk/3.1.415/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/home/draco/SSI/work/aries-acapy-controllers/AliceFaberAcmeDemo/controllers/faber-controller/FaberController/FaberController.csproj]
/usr/share/dotnet/sdk/3.1.415/NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [/home/draco/SSI/work/aries-acapy-controllers/AliceFaberAcmeDemo/controllers/faber-controller/FaberController/FaberController.csproj]
/usr/share/dotnet/sdk/3.1.415/NuGet.targets(128,5): error :   The remote certificate is invalid according to the validation procedure. [/home/draco/SSI/work/aries-acapy-controllers/AliceFaberAcmeDemo/controllers/faber-controller/FaberController/FaberController.csproj]

How to solved it? Thank you

**Comment by swcurran** [comment]
@amanji -- can you take a look at this? 

@KimhengSOK - Are you running this with Docker, or trying to run it directly on your machine?

**Comment by KimhengSOK** [comment]
> @amanji -- can you take a look at this?
> 
> @KimhengSOK - Are you running this with Docker, or trying to run it directly on your machine?

I am trying to run at my local machine, everything work, except Farber controller.
Look like there is some problem about certificate.

**Comment by swcurran** [comment]
Weird that a certificate issue is happening with Nuget.  A guess is it has to do with the recent change to the handling of the Let's Encrypt root CA credential.  This is fixed in browsers, but often browser-like HTTP resolvers are not getting updated as fast.

I think it is an upstream issue, and there's not much we can do.

Closing -- please reopen or add notes if you get more information.
