### ISSUE TITLE
run the project locally on ubuntu 18, I cannot create New Invitation

### ISSUE THREAD

**Issue by LeinaNazar** [hyperledger/aries-acapy-controllers#43]
I am trying to run the project locally on ubuntu 18, I cannot create New Invitation , and the indicate have red color not green.
when I run "dotnet run -p FaberController" in faber-controller folder and goto https://localhost:5001/ ,no action when I try to create new invitation
![ac-problem1](https://user-images.githubusercontent.com/20532799/143231450-b11f6197-e2c7-47e5-8cc4-eb2a9e813339.PNG)

**Comment by amanji** [comment]
You need to have an Agent running for the controller to connect to. Have you tried running the commands to spin up the project in a container or are you looking to develop the application locally?

**Comment by LeinaNazar** [comment]
Yes, I looking to develop the application locally. I want to change the attribute Name and Values.
I do not know how to  set the FABER_AGENT_HOST environment variable correctly

**Comment by LeinaNazar** [comment]
Now, I update run_demo by set FABER_AGENT_HOST environment variable , Am I set it correctly?
![image](https://user-images.githubusercontent.com/20532799/144554750-9c352bca-e68e-4136-879b-c3e445e80eaa.png)

**Comment by amanji** [comment]
You should be able to either export the variable before running the start command or inline:

```sh
$ LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ALICE_AGENT_HOST=<Your AWS Instance's Public DNS or IPv4> ./run_demo webstart
```

**Comment by swcurran** [comment]
Closing -- if you have any documentation guidance from others, please add a PR.
