### ISSUE TITLE
Command to run Alice/Faber/Acme demo failing when building controllers

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-acapy-controllers#77]
The build of the Alice/Faber/Acme controllers are failing -- unable to find a suitable version of "setuptools" for Alice, I think.

I tried to change the docker compose file to use the latest ACA-Py "dockerfile.demo" vs. the one from Petri Dish Dev, and that got passed the build error and the controllers started, but they failed issuing the credential.

Please investigate and update.

FYI -- @amanji

**Comment by amanji** [comment]
Fixed by #78
