### ISSUE TITLE
Alice controller fails while building

### ISSUE THREAD

**Issue by laserguy** [hyperledger/aries-acapy-controllers#99]
I get the following error while running the command: _LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo webstart_

> alice-controller@0.0.0 build /app
> ng build
> 
> This version of CLI is only compatible with Angular versions ^16.0.0,
> but Angular version 13.2.7 was found instead.
> 
> Please visit the link below to find instructions on how to update Angular.
> https://update.angular.io/
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 3
> npm ERR! alice-controller@0.0.0 build: `ng build`
> npm ERR! Exit status 3
> npm ERR!
> npm ERR! Failed at the alice-controller@0.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2024-01-16T11_13_39_583Z-debug.log
> ERROR: process "/bin/sh -c npm run build" did not complete successfully: exit code: 3

I installed the latest version of angular as well on my machine, but nothing changed.

I also tried to built locally but ran into same error:

> npm ERR! While resolving: alice-controller@0.0.0
> npm ERR! Found: @angular/compiler-cli@13.2.7
> npm ERR! node_modules/@angular/compiler-cli
> npm ERR!   dev @angular/compiler-cli@"~13.2.2" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/compiler-cli@"^16.0.0" from @angular-builders/custom-webpack@16.0.1
> npm ERR! node_modules/@angular-builders/custom-webpack
> npm ERR!   dev @angular-builders/custom-webpack@"^16.0.1" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by laserguy** [comment]
The same thing happens when I build through the docker

**Comment by Xuanye-Zhang** [comment]
I have have the sample problem also

**Comment by laserguy** [comment]
I reverted the code back to the previous commit(2 months back) for the alice-controller, now everything works.

**Comment by swcurran** [comment]
@amanji — something for you to look when you get a chance.  Or if anyone else wants to help out and fix this, please do.

Sorry for the issue.

**Comment by amanji** [comment]
I think Angular just needs an update. I'll take a crack at it during some down time.

**Comment by H4LL** [comment]
I took a crack at running and the angular issue persists. Looks like we need 16.0.0 or greater

**Comment by Maxino22** [comment]
facing the same issue tried runnning locally to no success

**Comment by swcurran** [comment]
@amanji — can you add this to your list to take a look at?  Thanks

**Comment by amanji** [comment]
Added to the project board.

**Comment by Maxino22** [comment]
I got mine working by using the angular update link provided https://update.angular.io/?v=13.0-16.0 updated from version 13 to 16 then updated the npm version via Dockerfile in the alice-controller `RUN npm install -g npm@10.7.0` and finally forced some dependencies `RUN npm install --force`
> facing the same issue tried runnning locally to no success

**Comment by swcurran** [comment]
@Maxino22 — great if you could put in a PR. If not, @amanji — what is needed is above ^^^^.

**Comment by amanji** [comment]
Resolved by #107
